apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: wf-bnch
  namespace: litmus
spec:
  entrypoint: argowf-chaos
  serviceAccountName: argo-chaos
  arguments:
    parameters:
      - name: appNamespace
        value: "apps"
      - name: adminModeNamespace
        value: "litmus"
      - name: appLabel
        value: "basic"
      - name: duration
        value: "2m"

  nodeSelector:
    kubernetes.io/os: linux
    role: "tools"

  tolerations:
    - key: tools
      operator: "Equal"
      value: "true"
      effect: NoSchedule

  # Note: it is for Step 6: the benchmark analysis demonstration

  templates:
    - name: argowf-chaos
      dag:
        tasks:

          - name: get-ingress-alb-workload-url
            templateRef:
              name: step6-templates
              template: get-ingress-alb-workload-url

          # Delete all the Workload pods to see the expected errors in the Benchmark results
          - name: drop-all-workload-pods
            dependencies: [ get-ingress-alb-workload-url ]
            templateRef:
              name: step2-templates
              template: cmd
            arguments:
              parameters:
                - name: cmd
                  value: |
                    set -x
                    kubectl delete pod -n {{workflow.parameters.appNamespace}} -l app.kubernetes.io/name={{workflow.parameters.appLabel}}

          - name: benchmark
            dependencies: [ get-ingress-alb-workload-url ]
            templateRef:
              name: step3-templates
              template: run-benchmark
            arguments:
              parameters:
                - name: bench-duration
                  value: "{{workflow.parameters.duration}}"
                - name: bench-rate
                  value: "10"
                - name: target-url
                  value: "{{tasks.get-ingress-alb-workload-url.outputs.result}}/hello?myName=MichaelK"

          - name: benchmark-reliability-verdict
            dependencies: [ drop-all-workload-pods, benchmark ]
            templateRef:
              name: step3-templates
              template: benchmark-reliability-verdict
            arguments:
              parameters:
                - name: benchmark-result
                  value: '{{tasks.benchmark.outputs.result}}'
