apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: wf-hg-sc
  namespace: litmus
spec:
  entrypoint: argowf-chaos
  serviceAccountName: argo-chaos
  arguments:
    parameters:
      - name: appNamespace
        value: "apps"
      - name: adminModeNamespace
        value: "litmus"
      - name: appLabel
        value: "basic"

      - name: chaos-duration
        value: "360" # 6 minutes

      - name: check-all-running-after-sec-of-chaos
        value: "300" # 5 minutes

      - name: litmus-experiment-id
        value: "strs-sclr"

  nodeSelector:
    kubernetes.io/os: linux
    role: "tools"

  tolerations:
    - key: tools
      operator: "Equal"
      value: "true"
      effect: NoSchedule

  # Note: it is for Step 5 ("hpa enabled + CA enabled")

  templates:
    - name: argowf-chaos
      dag:
        tasks:

          - name: cluster-autoscaler-log-daemon
            templateRef:
              name: step5-templates
              template: cluster-autoscaler-log-daemon

          - name: nodes-count-before-stress
            templateRef:
              name: step4-templates
              template: count-workload-nodes

          # CPU stress on all the Pods: Continuous Test

          - name: chaos-cpu-strs
            dependencies: [ nodes-count-before-stress ]
            templateRef:
              name: step4-templates
              template: litmus-cpu-hog
            arguments:
              parameters:
                - name: chaos-duration
                  value: "{{workflow.parameters.chaos-duration}}"
                - name: check-all-running-after-sec-of-chaos
                  value: "{{workflow.parameters.check-all-running-after-sec-of-chaos}}"
                - name: http-probe-mode
                  value: "Continuous"
                - name: experiment-id
                  value: "{{workflow.parameters.litmus-experiment-id}}"
                - name: pods-affected-perc
                  value: "100"
                - name: http-probe-url
                  value: "http://{{workflow.parameters.appLabel}}.{{workflow.parameters.appNamespace}}.svc.cluster.local:8080/hello"

          - name: wait-cpu-strs
            dependencies: [ chaos-cpu-strs ]
            templateRef:
              name: step1-templates
              template: await-litmus-result
            arguments:
              parameters:
                - name: experiment-id
                  value: "{{workflow.parameters.litmus-experiment-id}}"

          - name: litmus-intermediate-verdict
            dependencies: [ wait-cpu-strs ]
            templateRef:
              name: step1-templates
              template: litmus-reliability-verdict
            arguments:
              parameters:
                - name: experiment-id
                  value: "{{workflow.parameters.litmus-experiment-id}}"

          - name: nodes-count-after-stress
            dependencies: [ wait-cpu-strs ]
            templateRef:
              name: step4-templates
              template: count-workload-nodes

          # // TODO MKN: docu: related to the following settings in .../course/config/helm/values/cluster-autoscaler.yaml
          #    scale-down-unneeded-time: 1m
          #    scale-down-delay-after-add: 1m
          - name: let-cluster-autoscaler-scale-in
            dependencies: [ nodes-count-after-stress ]
            templateRef:
              name: step5-templates
              template: pause
            arguments:
              parameters:
                - name: duration
                  value: "5m"

          - name: nodes-count-after-scale-in
            dependencies: [ let-cluster-autoscaler-scale-in ]
            templateRef:
              name: step4-templates
              template: count-workload-nodes

          - name: nodes-scaling-intermediate-verdict
            dependencies: [ nodes-count-after-scale-in ]
            templateRef:
              name: step5-templates
              template: nodes-scaling-reliability-verdict
            arguments:
              parameters:
                - name: nodes-count-before-scale-out
                  value: '{{tasks.nodes-count-before-stress.outputs.result}}'
                - name: nodes-count-after-scale-out
                  value: '{{tasks.nodes-count-after-stress.outputs.result}}'
                - name: nodes-count-after-scale-in
                  value: '{{tasks.nodes-count-after-scale-in.outputs.result}}'

          - name: overall-reliability-verdict
            dependencies: [ nodes-scaling-intermediate-verdict, litmus-intermediate-verdict ]
            templateRef:
              name: step5-templates
              template: composite-reliability-verdict
            arguments:
              parameters:
                - name: upstream-verdicts
                  value: '{{tasks.litmus-intermediate-verdict.outputs.parameters.verdict}},{{tasks.nodes-scaling-intermediate-verdict.outputs.parameters.verdict}}'
